FROM eclipse-temurin:25-jre
WORKDIR /app

ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} /app/app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]

# Build & run:
#   docker build -t order-events-consumer:v1 .
#   docker run -p 8081:8081 order-events-consumer:v1