CREATE TABLE phone
(
    phone_id           INTEGER                     NOT NULL,
    phone_name         VARCHAR(255)                NOT NULL,
    phone_model        VARCHAR(255)                NOT NULL,
    phone_manufacturer VARCHAR(255)                NOT NULL,
    phone_price        BIGINT                      NOT NULL,
    order_event_id     INTEGER,
    created_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT pk_phone PRIMARY KEY (phone_id)
);

ALTER TABLE phone
    ADD CONSTRAINT uc_phone_order_event UNIQUE (order_event_id);

ALTER TABLE phone
    ADD CONSTRAINT FK_PHONE_ON_ORDER_EVENT FOREIGN KEY (order_event_id) REFERENCES order_event (order_event_id);
CREATE TABLE order_event
(
    order_event_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_type     VARCHAR(255)                             NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE              NOT NULL DEFAULT now(),
    updated_at     TIMESTAMP WITHOUT TIME ZONE              NOT NULL DEFAULT now(),
    CONSTRAINT pk_order_event PRIMARY KEY (order_event_id)
);
